export class Video {
    _id : string;
    user_id: string;
    name: string;
    type:string;
    source: string;
    fps:string;
    frame: string;
    roi: Array<String>;
    gps: string;
    protocol: string;
    interface: string;
    status:string;
    agent:string;
    peopleCount: boolean;
    vehicleCount: boolean;
    vehicleSpeed: boolean;
    vehicleTracking: boolean;
    peopleTracking: boolean;
    peopleList: boolean;
    vehicleList:boolean;
    faceRecognition: boolean;
    intrusionDetection: boolean;
    faceAnalytics : boolean;
    deepAssurance : boolean;
    carCrashDetection : boolean;
    wrongTurnDetection : boolean;
    parkingViolation : boolean;
    crowdDetection : boolean;
    fashion : boolean;
    litterDetection : boolean;
    helmetDetection : boolean;
    climbingDetection : boolean;
    theme : boolean;
    anpr : boolean;
    violence : boolean;
    media_type:string;
    algo: Array<String>;
}